info:
  title: Sheepdog
  version: 5.2.3
openapi: 3.1.0
paths:
  /_status:
    get:
      operationId: get_status__status_get
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: true
                title: Response Get Status  Status Get
                type: object
          description: Successful Response
      summary: Get Status
      tags:
      - System
  /_version:
    get:
      description: "Returns the version of Sheepdog\n---\ntags:\n    - system\nresponses:\n\
        \    200:\n    description: successful operation"
      operationId: get_version__version_get
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: true
                title: Response Get Version  Version Get
                type: object
          description: Successful Response
      summary: Get Version
      tags:
      - System
